DROP TABLE IF EXISTS ticket;

DROP TABLE IF EXISTS task_comment;

DROP TABLE IF EXISTS task_user;

DROP TABLE IF EXISTS task;

DROP TABLE IF EXISTS task_tag;

DROP TABLE IF EXISTS task_board;

DROP TABLE IF EXISTS message;

DROP TABLE IF EXISTS channel_user;

DROP TABLE IF EXISTS channel;

DROP TABLE IF EXISTS workspace_user;

DROP TABLE IF EXISTS workspace;

DROP TABLE IF EXISTS user_credential;

DROP TABLE IF EXISTS user_access;

DROP TABLE IF EXISTS user_detail;