version: "3.9"
services:
  mysql:
    image: mysql:8.0.26
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=straperdb
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_SOURCE=@(mysql:3306)/straperdb?parseTime=true
    depends_on: 
      - mysql
    entrypoint: ["/app/wait-for.sh","mysql:3306","--timeout=60","--","/app/start.sh"]
    command: ["/app/main"]