version: "3.9"
services:
  mysql:
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=straperdb
      - TZ=Asia/Singapore
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    environment:
      - DB_SOURCE=@(mysql:3306)/straperdb?parseTime=true&loc=Asia%2FSingapore
    depends_on:
      - mysql
    entrypoint: ["/app/wait-for.sh","mysql:3306","--timeout=60","--","/app/start.sh"]
    command: ["/app/main"]
